// IMU data-integrity check over a real SwingWindow (imu_refusion_check.h).
//
// The layer below this — refuseOrientation/parity on a bare sample vector — is
// covered by orientation_refuse_test. What was NOT covered, until eleven good
// wrist swings were badged ⚠ on the strength of it, is the part that decides
// WHICH lanes the parity question may be asked of at all. That decision is the
// whole value of the file, so it is what this test pins:
//
//   A. A host-fused (Witmotion) lane whose stored quaternion IS a Madgwick fusion
//      of its stored vectors passes, and reports itself as checked.
//   B. The same lane with the stored quaternion perturbed FAILS — the check can
//      actually detect an inconsistent record, so A is not vacuous.
//   C. A HackMotion lane is NOT CHECKED. Not "checked and passed": sourcesChecked
//      comes back 0 and warns() is false, so the caller writes no verdict at all.
//      A wG3 streams its own calibrated orientation and its accel column is
//      gravity-removed, so re-fusing it produces ~180° of disagreement — which is
//      exactly what shipped as a false warning on every wG3 shot ever captured.
//   D. A mixed window reports on the checkable half only — the skip is per-source,
//      not whole-check, and a wG3 sharing a window must not suppress the verdict
//      on the Witmotion lane beside it.
//
// Self-contained: the "stored live" quaternions are generated by running the real
// MadgwickFilter forward, so they are exact-by-construction and no recorded swing
// is needed. The window is built over RamPayloadSource — the same backing the
// offline re-analysis path uses — so no EventBuffer is involved.

#include "../imu_refusion_check.h"

#include "ram_payload_source.h"
#include "swing_window.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <memory>
#include <vector>

using pinpoint::DeviceKind;
using pinpoint::FormatDescriptor;
using pinpoint::ImuFormat;
using pinpoint::ImuSample;
using pinpoint::IndexEntry;
using pinpoint::RamPayloadSource;
using pinpoint::SourceId;
using pinpoint::SwingWindow;

static int g_fail = 0;

static void check(const char *label, bool ok, const char *detail)
{
    std::printf("  [%s] %-44s %s\n", ok ? "PASS" : "FAIL", label, detail);
    if (!ok) ++g_fail;
}

// Synthetic motion: constant gyro plus a slightly off-vertical accel, so the
// gravity correction stays active and the trajectory actually moves. Not physical
// — deterministic and filter-sensitive is all the check needs.
static constexpr uint32_t kRate = 200;             // Hz — matches the format below
static constexpr size_t   kN    = 400;             // 2 s
static constexpr float    kGx = 12.0f, kGy = 20.0f, kGz = -18.0f;   // deg/s
static constexpr float    kAx = 0.10f, kAy = -0.06f, kAz = 0.985f;  // g
static constexpr float    kD2R = 0.01745329251994329577f;

// One lane's worth of samples whose quaternion IS the Madgwick fusion of the accel
// and gyro beside it — generated exactly as ImuBase::fuseRawImu does (nominal dt,
// gyro converted deg/s -> rad/s, gravity seed on the first sample).
static std::vector<ImuSample> genHostFusedLane()
{
    std::vector<ImuSample> rows(kN);
    MadgwickFilter f;                              // production default beta
    const float dt = 1.0f / float(kRate);
    for (size_t i = 0; i < kN; ++i) {
        ImuSample &s = rows[i];
        s.accel_x = kAx; s.accel_y = kAy; s.accel_z = kAz;
        s.gyro_x  = kGx; s.gyro_y  = kGy; s.gyro_z  = kGz;
        if (i == 0)
            f.initFromAccel(kAx, kAy, kAz);
        f.update(kAx, kAy, kAz, kGx * kD2R, kGy * kD2R, kGz * kD2R, dt);
        s.quat_w = f.w(); s.quat_x = f.x(); s.quat_y = f.y(); s.quat_z = f.z();
    }
    return rows;
}

struct Lane {
    DeviceKind             device;
    std::vector<ImuSample> rows;
};

// Assemble a window from one or more IMU lanes. Every lane shares the timebase;
// sequence is the index into its own sample vector, matching how both real
// construction paths synthesise their IndexEntry rows.
static SwingWindow makeWindow(const std::vector<Lane> &lanes)
{
    auto src = std::make_unique<RamPayloadSource>();
    std::vector<IndexEntry> entries;
    int64_t tMax = 0;

    for (size_t li = 0; li < lanes.size(); ++li) {
        const SourceId id = SourceId(li);
        FormatDescriptor fd;
        fd.device        = lanes[li].device;
        fd.device_serial = "test-lane";
        ImuFormat imf{};
        imf.device         = lanes[li].device;
        imf.sample_rate_hz = kRate;
        imf.packet_bytes   = sizeof(ImuSample);
        imf.packet_schema  = "imu_sample_v2";
        fd.format          = imf;

        for (size_t i = 0; i < lanes[li].rows.size(); ++i) {
            const int64_t t = int64_t(double(i) * (1.0e6 / double(kRate)));
            entries.push_back(IndexEntry{ t, id, uint64_t(i) });
            if (t > tMax) tMax = t;
        }
        src->addImu(id, fd, lanes[li].rows);
    }
    // The window's own order must be ascending by timestamp — with two lanes on a
    // shared timebase, append order is per-lane, so sort as the real paths do.
    std::stable_sort(entries.begin(), entries.end(),
                     [](const IndexEntry &a, const IndexEntry &b) {
                         return a.timestamp_us < b.timestamp_us;
                     });
    return SwingWindow(std::move(src), std::move(entries), 0, tMax);
}

int main()
{
    std::printf("=== IMU re-fusion data-integrity check ===\n\n");
    char buf[200];

    // -- A. A faithfully-recorded host-fused lane passes --
    std::printf("-- A. host-fused lane, consistent record --\n");
    {
        const SwingWindow w = makeWindow({ { DeviceKind::IMU_WitMotion, genHostFusedLane() } });
        const pinpoint::ImuRefusionVerdict v = pinpoint::checkImuRefusion(w);
        std::snprintf(buf, sizeof buf, "checked %d, worst %.6f deg (threshold %.2f)",
                      v.sourcesChecked, v.worstMaxDeg, v.thresholdDeg);
        check("one source checked", v.sourcesChecked == 1, buf);
        check("parity holds",       v.ok,                  buf);
        check("no warning",         !v.warns(),            buf);
    }

    // -- B. Perturb the stored quaternion and it must FAIL --
    // Without this, A would pass just as happily against a check that never
    // compared anything.
    std::printf("\n-- B. host-fused lane, quaternion inconsistent with the vectors --\n");
    {
        std::vector<ImuSample> rows = genHostFusedLane();
        // A few degrees of rotation injected halfway through — far above the 0.5°
        // boundary, far below the ~180° saturation a wrong-device check produces.
        for (size_t i = kN / 2; i < kN; ++i) {
            const float w0 = rows[i].quat_w, x0 = rows[i].quat_x;
            rows[i].quat_w = w0 * 0.999f - x0 * 0.0436f;   // ~5 deg about X
            rows[i].quat_x = x0 * 0.999f + w0 * 0.0436f;
        }
        const SwingWindow w = makeWindow({ { DeviceKind::IMU_WitMotion, std::move(rows) } });
        const pinpoint::ImuRefusionVerdict v = pinpoint::checkImuRefusion(w);
        std::snprintf(buf, sizeof buf, "checked %d, worst %.4f deg", v.sourcesChecked, v.worstMaxDeg);
        check("one source checked", v.sourcesChecked == 1,   buf);
        check("parity fails",       !v.ok,                   buf);
        check("warns",              v.warns(),               buf);
        check("failure is marginal, not saturated", v.worstMaxDeg < 90.0, buf);
    }

    // -- C. A HackMotion lane is not checkable, and must not be checked --
    // The regression this whole test exists for. Feeding a wG3's samples to the
    // check yields ~180° and a ⚠ badge on a perfectly consistent recording.
    std::printf("\n-- C. HackMotion lane, not checkable --\n");
    {
        const SwingWindow w = makeWindow({ { DeviceKind::IMU_HackMotion, genHostFusedLane() } });
        const pinpoint::ImuRefusionVerdict v = pinpoint::checkImuRefusion(w);
        std::snprintf(buf, sizeof buf, "checked %d, worst %.4f deg, ok=%d",
                      v.sourcesChecked, v.worstMaxDeg, int(v.ok));
        check("nothing checked",        v.sourcesChecked == 0, buf);
        check("no warning raised",      !v.warns(),            buf);
        check("no distance reported",   v.worstMaxDeg == 0.0,  buf);
    }

    // -- D. Mixed window: the skip is per-source, not whole-check --
    std::printf("\n-- D. mixed window, checkable lane beside an uncheckable one --\n");
    {
        const SwingWindow w = makeWindow({ { DeviceKind::IMU_HackMotion, genHostFusedLane() },
                                           { DeviceKind::IMU_WitMotion,  genHostFusedLane() } });
        const pinpoint::ImuRefusionVerdict v = pinpoint::checkImuRefusion(w);
        std::snprintf(buf, sizeof buf, "checked %d of 2 lanes, worst %.6f deg",
                      v.sourcesChecked, v.worstMaxDeg);
        check("checkable half checked", v.sourcesChecked == 1, buf);
        check("wG3 did not fail it",    v.ok,                  buf);
        check("no warning",             !v.warns(),            buf);
    }

    std::printf("\n%s (%d failure%s)\n", g_fail ? "FAILED" : "OK",
                g_fail, g_fail == 1 ? "" : "s");
    return g_fail ? 1 : 0;
}
